import type { Metadata } from "next";

import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";

import { fontVariables } from "@/fonts";
import { cn } from "@/lib/utils";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("flex min-h-dvh flex-col antialiased", fontVariables)}
      >
        <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </Provider>
      </body>
    </html>
  );
}
